First:
	gcc main.c input.c rem_space.c cd.c ls.c big_ls.c echo.c pwd.c fg.c bg.c proc.c proc_exit.c redir1.c redir2.c redir3.c setenv.c unsetenv.c parsepipe.c jobs.c kjobs.c overkill.c sigint.c sigtstp.c bgg.c fgg.c pipe.c callcd.c -L/usr/include -lreadline -g -o main

